# 🚀 **Staging Deployment Patch**
# Staging-specific deployment overrides
# Interview Story: "This overrides the base deployment with staging-specific settings"

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-frontend
  namespace: ecommerce-staging
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: ecommerce-app
        resources:
          limits:
            cpu: 750m
            memory: 1.5Gi
          requests:
            cpu: 375m
            memory: 750Mi
        env:
        - name: NODE_ENV
          value: "production"
        - name: LOG_LEVEL
          value: "info"
