apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce-staging

resources:
  - ../../base

patchesStrategicMerge:
  - configmap-patch.yaml
  - deployment-patch.yaml

configMapGenerator:
  - name: ecommerce-config
    behavior: replace
    literals:
      - NODE_ENV=production
      - NEXT_PUBLIC_APP_URL=https://staging.ecommerce.company.com
      - NEXT_PUBLIC_API_URL=https://staging.ecommerce.company.com/api
      - NEXTAUTH_URL=https://staging.ecommerce.company.com
      - DATABASE_URL=postgresql://postgres:${DATABASE_PASSWORD}@postgres-service:5432/ecommerce_staging
      - REDIS_URL=redis://redis-service:6379
      - LOG_LEVEL=debug
      - ENABLE_ANALYTICS=false

images:
  - name: ecommerce-production-client
    newTag: staging-latest

replicas:
  - name: ecommerce-frontend
    count: 2