# 🎭 **Staging Environment Kustomization**
# Staging-specific configuration
# Interview Story: "This is our staging kitchen where we test recipes before serving to customers"

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base configuration
bases:
  - ../../base

# Staging-specific patches
patchesStrategicMerge:
  - configmap-patch.yaml
  - deployment-patch.yaml

# Staging-specific resources
resources:
  - namespace-patch.yaml

# Staging-specific labels
commonLabels:
  environment: staging
  purpose: testing

# Staging-specific annotations
commonAnnotations:
  environment: staging
  purpose: testing

# Staging-specific namespace
namespace: ecommerce-staging

# Staging-specific image tags
images:
  - name: pavandoc1990/ecommerce-production-client
    newTag: staging-latest
