# 🚀 **Simple E-commerce Kubernetes Deployment**
# Industry-standard deployment for local development
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-frontend
  namespace: ecommerce-production
  labels:
    app: ecommerce
    component: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ecommerce
      component: frontend
  template:
    metadata:
      labels:
        app: ecommerce
        component: frontend
    spec:
      containers:
      - name: ecommerce-app
        image: ecommerce-client:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: DATABASE_URL
          value: "postgresql://ecommerce:password@postgres-service:5432/ecommerce_db"
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: NEXTAUTH_URL
          value: "http://localhost:3000"
        - name: NEXTAUTH_SECRET
          value: "your-nextauth-secret-please-change-in-production"
        - name: STRIPE_SECRET_KEY
          value: "sk_test_stripe_secret_key"
        - name: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
          value: "pk_test_stripe_publishable_key"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-frontend-service
  namespace: ecommerce-production
spec:
  selector:
    app: ecommerce
    component: frontend
  ports:
  - name: http
    port: 80
    targetPort: 3000
  type: ClusterIP
