apiVersion: v1
kind: Secret
metadata:
  name: datadog-secret
  namespace: monitoring
type: Opaque
data:
  # Base64 encoded DataDog API key
  # Replace with your actual DataDog API key
  api-key: <BASE64_ENCODED_DATADOG_API_KEY>
