# ⚙️ **Production ConfigMap**
# Non-sensitive configuration for production deployment
# Interview Story: "This contains all the non-secret configuration for our production recipe"

apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce-production
  labels:
    app: ecommerce
    environment: production
data:
  # Application Configuration
  NODE_ENV: "production"
  NEXT_PUBLIC_APP_URL: "https://ecommerce.yourdomain.com"
  NEXT_PUBLIC_API_URL: "https://ecommerce.yourdomain.com/api"
  
  # Database Configuration
  POSTGRES_DB: "ecommerce_db"
  POSTGRES_USER: "ecommerce"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  
  # Redis Configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  
  # Monitoring Configuration
  PROMETHEUS_ENDPOINT: "http://prometheus-service:9090"
  GRAFANA_ENDPOINT: "http://grafana-service:3000"
  JAEGER_ENDPOINT: "http://jaeger-service:14268"
  
  # Logging Configuration
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  
  # Performance Configuration
  CACHE_TTL: "3600"
  SESSION_TIMEOUT: "86400"
  MAX_CONNECTIONS: "100"
  
  # Security Configuration
  CORS_ORIGIN: "https://ecommerce.yourdomain.com"
  RATE_LIMIT_WINDOW: "900000"
  RATE_LIMIT_MAX: "100"
  
  # Feature Flags
  ENABLE_ANALYTICS: "true"
  ENABLE_MONITORING: "true"
  ENABLE_TRACING: "true"
  ENABLE_CACHING: "true"
