# 🔐 **Production Secrets**
# Sensitive configuration for production deployment
# Interview Story: "This contains all the secret ingredients for our production recipe"

apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce-production
  labels:
    app: ecommerce
    environment: production
type: Opaque
data:
  # Database URL (base64 encoded)
  # Format: postgresql://username:password@host:port/database
  database-url: cG9zdGdyZXNxbDovL2Vjb21tZXJjZTpwYXNzd29yZEBwb3N0Z3Jlcy1zZXJ2aWNlOjU0MzIvZWNvbW1lcmNlX2Ri
  
  # Redis URL (base64 encoded)
  # Format: redis://password@host:port
  redis-url: cmVkaXM6Ly9yZWRpc19wYXNzd29yZEByZWRpcy1zZXJ2aWNlOjYzNzk=
  
  # NextAuth Secret (base64 encoded)
  # Generate with: openssl rand -base64 32
  nextauth-secret: eW91ci1uZXh0YXV0aC1zZWNyZXQta2V5LWNoYW5nZS1pbi1wcm9kdWN0aW9u
  
  # Stripe Keys (base64 encoded)
  # Replace with your actual Stripe keys
  stripe-secret-key: c2tfdGVzdF95b3VyX3N0cmlwZV9zZWNyZXRfa2V5
  stripe-publishable-key: cGtfdGVzdF95b3VyX3N0cmlwZV9wdWJsaXNoYWJsZV9rZXk=
  
  # JWT Secret (base64 encoded)
  # Generate with: openssl rand -base64 32
  jwt-secret: eW91ci1qd3Qtc2VjcmV0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==
  
  # Encryption Key (base64 encoded)
  # Generate with: openssl rand -base64 32
  encryption-key: eW91ci1lbmNyeXB0aW9uLWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==

---
# 🔐 **Production ConfigMap**
# Non-sensitive configuration for production deployment
apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce-production
  labels:
    app: ecommerce
    environment: production
data:
  # Application Configuration
  NODE_ENV: "production"
  NEXT_PUBLIC_APP_URL: "https://ecommerce.yourdomain.com"
  NEXT_PUBLIC_API_URL: "https://ecommerce.yourdomain.com/api"
  
  # Database Configuration
  POSTGRES_DB: "ecommerce_db"
  POSTGRES_USER: "ecommerce"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  
  # Redis Configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: "redis_password"
  
  # Monitoring Configuration
  PROMETHEUS_ENDPOINT: "http://prometheus-service:9090"
  GRAFANA_ENDPOINT: "http://grafana-service:3000"
  JAEGER_ENDPOINT: "http://jaeger-service:14268"
  
  # Logging Configuration
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  
  # Performance Configuration
  CACHE_TTL: "3600"
  SESSION_TIMEOUT: "86400"
  MAX_CONNECTIONS: "100"
