apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config-staging
  namespace: ecommerce-staging
  labels:
    app: ecommerce
    component: config
    environment: staging
    managed-by: kustomize
data:
  # Staging Environment Configuration
  NODE_ENV: "production"
  
  # Application URLs - Staging Specific
  NEXT_PUBLIC_APP_URL: "https://staging.ecommerce.company.com"
  NEXT_PUBLIC_API_URL: "https://staging.ecommerce.company.com/api"
  NEXTAUTH_URL: "https://staging.ecommerce.company.com"
  
  # Database Configuration
  DATABASE_URL: "postgresql://postgres:${DATABASE_PASSWORD}@postgres-service:5432/ecommerce_staging"
  POSTGRES_DB: "ecommerce_staging"
  POSTGRES_USER: "postgres"
  POSTGRES_HOST: "postgres-service"
  
  # Redis Configuration
  REDIS_URL: "redis://redis-service:6379"
  
  # Session Configuration
  SESSION_SECRET: "staging-session-secret-key"
  
  # Monitoring and Logging
  LOG_LEVEL: "debug"
  ENABLE_METRICS: "true"
  
  # Security Configuration
  CORS_ORIGINS: "https://staging.ecommerce.company.com"
  RATE_LIMIT_ENABLED: "true"
  
  # Feature Flags
  ENABLE_ANALYTICS: "false"
  ENABLE_CACHING: "true"
  ENABLE_CDN: "false"
