# DataDog Cluster Agent for Kubernetes State Metrics
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datadog-cluster-agent
  namespace: monitoring
  labels:
    app: datadog-cluster-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datadog-cluster-agent
  template:
    metadata:
      labels:
        app: datadog-cluster-agent
    spec:
      serviceAccountName: datadog-agent
      containers:
      - name: datadog-cluster-agent
        image: datadog/cluster-agent:1.18.0
        imagePullPolicy: IfNotPresent
        env:
        - name: DD_CLUSTER_NAME
          value: "ecommerce-k8s"
        - name: DD_API_KEY
          valueFrom:
            secretKeyRef:
              name: datadog-secret
              key: api-key
        - name: DD_SITE
          value: "us5.datadoghq.com"
        - name: DD_COLLECT_KUBERNETES_EVENTS
          value: "true"
        - name: DD_COLLECT_KUBERNETES_METRICS
          value: "true"
        - name: DD_KUBERNETES_COLLECT_METADATA_TAGS
          value: "true"
        - name: DD_ORCHESTRATOR_EXPLORER_ENABLED
          value: "true"
        - name: DD_ORCHESTRATOR_CLUSTER_NAME
          value: "ecommerce-k8s"
        - name: DD_CLUSTER_AGENT_ENABLED
          value: "true"
        - name: DD_CLUSTER_AGENT_KUBERNETES_METRICS_ENABLED
          value: "true"
        - name: DD_CLUSTER_AGENT_METRICS_PROVIDER_ENABLED
          value: "true"
        - name: DD_CLUSTER_AGENT_METRICS_PROVIDER_PORT
          value: "8443"
        ports:
        - containerPort: 5005
          name: http
        - containerPort: 5006
          name: https
        - containerPort: 8443
          name: metrics
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5005
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 5005
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: datadog-cluster-agent
  namespace: monitoring
  labels:
    app: datadog-cluster-agent
spec:
  ports:
  - port: 5005
    targetPort: 5005
    protocol: TCP
    name: http
  - port: 5006
    targetPort: 5006
    protocol: TCP
    name: https
  - port: 8443
    targetPort: 8443
    protocol: TCP
    name: metrics
  selector:
    app: datadog-cluster-agent
