# 🚀 **Production Deployment Patch**
# Production-specific deployment overrides
# Interview Story: "This overrides the base deployment with production-specific settings"

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-frontend
  namespace: ecommerce-production
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: ecommerce-app
        resources:
          limits:
            cpu: 2000m
            memory: 4Gi
          requests:
            cpu: 1000m
            memory: 2Gi
        env:
        - name: NODE_ENV
          value: "production"
        - name: LOG_LEVEL
          value: "info"
        - name: ENABLE_ANALYTICS
          value: "true"
        - name: ENABLE_MONITORING
          value: "true"
        - name: ENABLE_TRACING
          value: "true"
        - name: ENABLE_CACHING
          value: "true"
